# 1. Create a 3x3 matrix array with values ranging from 2 to 10.
2. Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. For instance:
   Original array [1, 2, 3, 4] 
   Array converted to a float type: [ 1. 2. 3. 4.]
3. Write a Numpy program to append values to the end of an array. For instance:
   Original array: [10, 20, 30] 
   After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.
5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:
   a. Extract the 1st row from the array.
   b. Extract the last element from the array.

In [1]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr1= arr.astype(float)
arr1

array([1., 2., 3., 4.])

In [4]:
a=[10,20,30]

In [5]:
a.append(40)
a.append(50)
a.append(60)
a.append(70)
a.append(80)
a.append(90)
a

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [6]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [7]:
sumarray=x + y
print(sumarray)

[5 7 9]


In [8]:
z=np.arange(10,100,10)
array1=z.reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
array1[0]

array([10, 20, 30])

In [10]:
array1[2,2]

90